// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FalconSearchStoreInfo struct {
	StoreName            string   `protobuf:"bytes,1,opt,name=StoreName,proto3" json:"StoreName,omitempty"`
	StoreLength          int64    `protobuf:"varint,2,opt,name=StoreLength,proto3" json:"StoreLength,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FalconSearchStoreInfo) Reset()         { *m = FalconSearchStoreInfo{} }
func (m *FalconSearchStoreInfo) String() string { return proto.CompactTextString(m) }
func (*FalconSearchStoreInfo) ProtoMessage()    {}
func (*FalconSearchStoreInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *FalconSearchStoreInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FalconSearchStoreInfo.Unmarshal(m, b)
}
func (m *FalconSearchStoreInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FalconSearchStoreInfo.Marshal(b, m, deterministic)
}
func (m *FalconSearchStoreInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FalconSearchStoreInfo.Merge(m, src)
}
func (m *FalconSearchStoreInfo) XXX_Size() int {
	return xxx_messageInfo_FalconSearchStoreInfo.Size(m)
}
func (m *FalconSearchStoreInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FalconSearchStoreInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FalconSearchStoreInfo proto.InternalMessageInfo

func (m *FalconSearchStoreInfo) GetStoreName() string {
	if m != nil {
		return m.StoreName
	}
	return ""
}

func (m *FalconSearchStoreInfo) GetStoreLength() int64 {
	if m != nil {
		return m.StoreLength
	}
	return 0
}

type BinlogMessage struct {
	LogId                int64    `protobuf:"varint,1,opt,name=LogId,proto3" json:"LogId,omitempty"`
	LogTimestamp         int64    `protobuf:"varint,2,opt,name=LogTimestamp,proto3" json:"LogTimestamp,omitempty"`
	LogDetail            []byte   `protobuf:"bytes,3,opt,name=LogDetail,proto3" json:"LogDetail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BinlogMessage) Reset()         { *m = BinlogMessage{} }
func (m *BinlogMessage) String() string { return proto.CompactTextString(m) }
func (*BinlogMessage) ProtoMessage()    {}
func (*BinlogMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *BinlogMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BinlogMessage.Unmarshal(m, b)
}
func (m *BinlogMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BinlogMessage.Marshal(b, m, deterministic)
}
func (m *BinlogMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BinlogMessage.Merge(m, src)
}
func (m *BinlogMessage) XXX_Size() int {
	return xxx_messageInfo_BinlogMessage.Size(m)
}
func (m *BinlogMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BinlogMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BinlogMessage proto.InternalMessageInfo

func (m *BinlogMessage) GetLogId() int64 {
	if m != nil {
		return m.LogId
	}
	return 0
}

func (m *BinlogMessage) GetLogTimestamp() int64 {
	if m != nil {
		return m.LogTimestamp
	}
	return 0
}

func (m *BinlogMessage) GetLogDetail() []byte {
	if m != nil {
		return m.LogDetail
	}
	return nil
}

type DictValue struct {
	Val                  uint64   `protobuf:"varint,1,opt,name=Val,proto3" json:"Val,omitempty"`
	ExtVal               uint64   `protobuf:"varint,2,opt,name=ExtVal,proto3" json:"ExtVal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DictValue) Reset()         { *m = DictValue{} }
func (m *DictValue) String() string { return proto.CompactTextString(m) }
func (*DictValue) ProtoMessage()    {}
func (*DictValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *DictValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DictValue.Unmarshal(m, b)
}
func (m *DictValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DictValue.Marshal(b, m, deterministic)
}
func (m *DictValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DictValue.Merge(m, src)
}
func (m *DictValue) XXX_Size() int {
	return xxx_messageInfo_DictValue.Size(m)
}
func (m *DictValue) XXX_DiscardUnknown() {
	xxx_messageInfo_DictValue.DiscardUnknown(m)
}

var xxx_messageInfo_DictValue proto.InternalMessageInfo

func (m *DictValue) GetVal() uint64 {
	if m != nil {
		return m.Val
	}
	return 0
}

func (m *DictValue) GetExtVal() uint64 {
	if m != nil {
		return m.ExtVal
	}
	return 0
}

type DocId struct {
	DocID                uint32   `protobuf:"varint,1,opt,name=DocID,proto3" json:"DocID,omitempty"`
	Weight               uint32   `protobuf:"varint,2,opt,name=Weight,proto3" json:"Weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DocId) Reset()         { *m = DocId{} }
func (m *DocId) String() string { return proto.CompactTextString(m) }
func (*DocId) ProtoMessage()    {}
func (*DocId) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *DocId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocId.Unmarshal(m, b)
}
func (m *DocId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocId.Marshal(b, m, deterministic)
}
func (m *DocId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocId.Merge(m, src)
}
func (m *DocId) XXX_Size() int {
	return xxx_messageInfo_DocId.Size(m)
}
func (m *DocId) XXX_DiscardUnknown() {
	xxx_messageInfo_DocId.DiscardUnknown(m)
}

var xxx_messageInfo_DocId proto.InternalMessageInfo

func (m *DocId) GetDocID() uint32 {
	if m != nil {
		return m.DocID
	}
	return 0
}

func (m *DocId) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type FieldValue struct {
	Field                string   `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FieldValue) Reset()         { *m = FieldValue{} }
func (m *FieldValue) String() string { return proto.CompactTextString(m) }
func (*FieldValue) ProtoMessage()    {}
func (*FieldValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *FieldValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldValue.Unmarshal(m, b)
}
func (m *FieldValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldValue.Marshal(b, m, deterministic)
}
func (m *FieldValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldValue.Merge(m, src)
}
func (m *FieldValue) XXX_Size() int {
	return xxx_messageInfo_FieldValue.Size(m)
}
func (m *FieldValue) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldValue.DiscardUnknown(m)
}

var xxx_messageInfo_FieldValue proto.InternalMessageInfo

func (m *FieldValue) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *FieldValue) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type Document struct {
	Val                  []*FieldValue `protobuf:"bytes,1,rep,name=val,proto3" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Document) Reset()         { *m = Document{} }
func (m *Document) String() string { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()    {}
func (*Document) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *Document) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Document.Unmarshal(m, b)
}
func (m *Document) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Document.Marshal(b, m, deterministic)
}
func (m *Document) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Document.Merge(m, src)
}
func (m *Document) XXX_Size() int {
	return xxx_messageInfo_Document.Size(m)
}
func (m *Document) XXX_DiscardUnknown() {
	xxx_messageInfo_Document.DiscardUnknown(m)
}

var xxx_messageInfo_Document proto.InternalMessageInfo

func (m *Document) GetVal() []*FieldValue {
	if m != nil {
		return m.Val
	}
	return nil
}

func init() {
	proto.RegisterType((*FalconSearchStoreInfo)(nil), "message.FalconSearchStoreInfo")
	proto.RegisterType((*BinlogMessage)(nil), "message.BinlogMessage")
	proto.RegisterType((*DictValue)(nil), "message.DictValue")
	proto.RegisterType((*DocId)(nil), "message.DocId")
	proto.RegisterType((*FieldValue)(nil), "message.FieldValue")
	proto.RegisterType((*Document)(nil), "message.Document")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0xa9, 0xd9, 0xa6, 0x7b, 0x5b, 0x41, 0xe2, 0x94, 0x1d, 0x3c, 0x94, 0x80, 0xd0, 0xd3,
	0x40, 0x65, 0xe0, 0x59, 0xea, 0x60, 0x50, 0x3d, 0x64, 0xb2, 0x9d, 0x63, 0xf7, 0x96, 0x06, 0xd2,
	0x66, 0xb4, 0xd9, 0xf0, 0xcf, 0x97, 0x24, 0x95, 0xea, 0x2d, 0xbf, 0xef, 0xf1, 0x7d, 0xef, 0x23,
	0x0f, 0xe2, 0x0a, 0xdb, 0x56, 0x48, 0x5c, 0x1c, 0x1b, 0x63, 0x0d, 0xbd, 0xec, 0x90, 0xed, 0xe0,
	0x76, 0x25, 0x74, 0x61, 0xea, 0x0d, 0x8a, 0xa6, 0x28, 0x37, 0xd6, 0x34, 0xb8, 0xae, 0x0f, 0x86,
	0xde, 0xc3, 0xd8, 0xc3, 0x87, 0xa8, 0x70, 0x1e, 0x25, 0x51, 0x3a, 0xe6, 0xbd, 0x40, 0x13, 0x98,
	0x78, 0xc8, 0xb1, 0x96, 0xb6, 0x9c, 0x5f, 0x24, 0x51, 0x4a, 0xf8, 0x5f, 0x89, 0x49, 0x88, 0x5f,
	0x55, 0xad, 0x8d, 0x7c, 0x0f, 0x9b, 0xe8, 0x0c, 0x86, 0xb9, 0x91, 0xeb, 0xbd, 0x0f, 0x23, 0x3c,
	0x00, 0x65, 0x30, 0xcd, 0x8d, 0xfc, 0x54, 0x15, 0xb6, 0x56, 0x54, 0xc7, 0x2e, 0xe9, 0x9f, 0xe6,
	0xaa, 0xe4, 0x46, 0x66, 0x68, 0x85, 0xd2, 0x73, 0x92, 0x44, 0xe9, 0x94, 0xf7, 0x02, 0x5b, 0xc2,
	0x38, 0x53, 0x85, 0xdd, 0x0a, 0x7d, 0x42, 0x7a, 0x0d, 0x64, 0x2b, 0xb4, 0x5f, 0x31, 0xe0, 0xee,
	0x49, 0xef, 0x60, 0xf4, 0xf6, 0xed, 0xa6, 0x3e, 0x7a, 0xc0, 0x3b, 0x62, 0x4b, 0x18, 0x66, 0xa6,
	0x58, 0xef, 0x5d, 0x2f, 0xf7, 0xc8, 0xbc, 0x29, 0xe6, 0x01, 0x9c, 0x6d, 0x87, 0x4a, 0x96, 0xd6,
	0xdb, 0x62, 0xde, 0x11, 0x7b, 0x01, 0x58, 0x29, 0xd4, 0xfb, 0xb0, 0x6e, 0x06, 0xc3, 0x83, 0xa3,
	0xee, 0x83, 0x02, 0x38, 0xf5, 0xec, 0xc6, 0xde, 0x3a, 0xe5, 0x01, 0xd8, 0x23, 0x5c, 0x65, 0xa6,
	0x38, 0x55, 0x58, 0x5b, 0xfa, 0x00, 0xe4, 0xec, 0x6b, 0x92, 0x74, 0xf2, 0x74, 0xb3, 0xf8, 0xbd,
	0x4d, 0x9f, 0xcc, 0xdd, 0xfc, 0x6b, 0xe4, 0x8f, 0xf5, 0xfc, 0x13, 0x00, 0x00, 0xff, 0xff, 0x11,
	0x58, 0x9e, 0xe8, 0xbd, 0x01, 0x00, 0x00,
}
