// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FalconSearchStoreInfo struct {
	StoreName            string   `protobuf:"bytes,1,opt,name=StoreName,proto3" json:"StoreName,omitempty"`
	StoreLength          int64    `protobuf:"varint,2,opt,name=StoreLength,proto3" json:"StoreLength,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FalconSearchStoreInfo) Reset()         { *m = FalconSearchStoreInfo{} }
func (m *FalconSearchStoreInfo) String() string { return proto.CompactTextString(m) }
func (*FalconSearchStoreInfo) ProtoMessage()    {}
func (*FalconSearchStoreInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *FalconSearchStoreInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FalconSearchStoreInfo.Unmarshal(m, b)
}
func (m *FalconSearchStoreInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FalconSearchStoreInfo.Marshal(b, m, deterministic)
}
func (m *FalconSearchStoreInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FalconSearchStoreInfo.Merge(m, src)
}
func (m *FalconSearchStoreInfo) XXX_Size() int {
	return xxx_messageInfo_FalconSearchStoreInfo.Size(m)
}
func (m *FalconSearchStoreInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FalconSearchStoreInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FalconSearchStoreInfo proto.InternalMessageInfo

func (m *FalconSearchStoreInfo) GetStoreName() string {
	if m != nil {
		return m.StoreName
	}
	return ""
}

func (m *FalconSearchStoreInfo) GetStoreLength() int64 {
	if m != nil {
		return m.StoreLength
	}
	return 0
}

type BinlogMessage struct {
	LogId                int64    `protobuf:"varint,1,opt,name=LogId,proto3" json:"LogId,omitempty"`
	LogTimestamp         int64    `protobuf:"varint,2,opt,name=LogTimestamp,proto3" json:"LogTimestamp,omitempty"`
	LogDetail            []byte   `protobuf:"bytes,3,opt,name=LogDetail,proto3" json:"LogDetail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BinlogMessage) Reset()         { *m = BinlogMessage{} }
func (m *BinlogMessage) String() string { return proto.CompactTextString(m) }
func (*BinlogMessage) ProtoMessage()    {}
func (*BinlogMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *BinlogMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BinlogMessage.Unmarshal(m, b)
}
func (m *BinlogMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BinlogMessage.Marshal(b, m, deterministic)
}
func (m *BinlogMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BinlogMessage.Merge(m, src)
}
func (m *BinlogMessage) XXX_Size() int {
	return xxx_messageInfo_BinlogMessage.Size(m)
}
func (m *BinlogMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BinlogMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BinlogMessage proto.InternalMessageInfo

func (m *BinlogMessage) GetLogId() int64 {
	if m != nil {
		return m.LogId
	}
	return 0
}

func (m *BinlogMessage) GetLogTimestamp() int64 {
	if m != nil {
		return m.LogTimestamp
	}
	return 0
}

func (m *BinlogMessage) GetLogDetail() []byte {
	if m != nil {
		return m.LogDetail
	}
	return nil
}

func init() {
	proto.RegisterType((*FalconSearchStoreInfo)(nil), "message.FalconSearchStoreInfo")
	proto.RegisterType((*BinlogMessage)(nil), "message.BinlogMessage")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0xc2, 0xb9,
	0x44, 0xdd, 0x12, 0x73, 0x92, 0xf3, 0xf3, 0x82, 0x53, 0x13, 0x8b, 0x92, 0x33, 0x82, 0x4b, 0xf2,
	0x8b, 0x52, 0x3d, 0xf3, 0xd2, 0xf2, 0x85, 0x64, 0xb8, 0x38, 0xc1, 0x1c, 0xbf, 0xc4, 0xdc, 0x54,
	0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x84, 0x80, 0x90, 0x02, 0x17, 0x37, 0x98, 0xe3, 0x93,
	0x9a, 0x97, 0x5e, 0x92, 0x21, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x1c, 0x84, 0x2c, 0xa4, 0x94, 0xce,
	0xc5, 0xeb, 0x94, 0x99, 0x97, 0x93, 0x9f, 0xee, 0x0b, 0xb1, 0x49, 0x48, 0x84, 0x8b, 0xd5, 0x27,
	0x3f, 0xdd, 0x33, 0x05, 0x6c, 0x18, 0x73, 0x10, 0x84, 0x23, 0xa4, 0xc4, 0xc5, 0xe3, 0x93, 0x9f,
	0x1e, 0x92, 0x99, 0x9b, 0x5a, 0x5c, 0x92, 0x98, 0x5b, 0x00, 0x35, 0x09, 0x45, 0x0c, 0xe4, 0x14,
	0x9f, 0xfc, 0x74, 0x97, 0xd4, 0x92, 0xc4, 0xcc, 0x1c, 0x09, 0x66, 0x05, 0x46, 0x0d, 0x9e, 0x20,
	0x84, 0x40, 0x12, 0x1b, 0xd8, 0x47, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xaf, 0xd0, 0x14,
	0xd7, 0xe2, 0x00, 0x00, 0x00,
}
